apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-api
  labels:
    app: medical-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medical-api
  template:
    metadata:
      labels:
        app: medical-api
    spec:
      containers:
      - name: medical-api
        image: medical-api:latest
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: medical-api-secrets
              key: mongodb_uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: medical-api-secrets
              key: jwt_secret
        - name: JWT_LIFETIME
          value: "7d"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5