apiVersion: v1
kind: Service
metadata:
  name: medical-api-service
  labels:
    app: medical-api
spec:
  selector:
    app: medical-api
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer